# Stage 5: assemble assets/data.js — the single payload every data-driven tab reads.
# Sources: data.json (scrape + scores), features.json (feature evidence), ours.json (our app, checked on the
# emulator), listing.json (the proposed copy and the written sections). Nothing is typed twice: if a number is
# wrong here, it is wrong in the JSON, and the JSON came from Google Play.
#
#   powershell -ExecutionPolicy Bypass -File build.ps1

$ErrorActionPreference = 'Stop'
$OUT = $PSScriptRoot
$REPO = Split-Path (Split-Path $OUT -Parent) -Parent

function Read-Json([string]$n) {
  # The comma keeps an array an array on the way out of the function; without it PowerShell
  # flattens the result into the output stream and the caller gets one joined string.
  $t = Get-Content (Join-Path $OUT $n) -Raw -Encoding UTF8
  , ($t | ConvertFrom-Json)
}

$data = Read-Json 'data.json'
$features = Read-Json 'features.json'
$ours = Read-Json 'ours.json'
$listing = Read-Json 'listing.json'
$graphics = Read-Json 'graphics.json'
$gnotes = Read-Json 'graphics-notes.json'

# Our own column in the feature matrix is the emulator check, not the listing text.
$ourIdx = 0
for ($i = 0; $i -lt $features.features.Count; $i++) {
  $name = $features.features[$i][1]
  $truth = $ours.features.$name
  if ($null -ne $truth) {
    $features.features[$i][2][$ourIdx] = [int]$truth
    $ev = $ours.evidence.$name
    if ($ev) { $features.features[$i][3][$ourIdx] = $ev }
  }
}

$payload = [ordered]@{
  data     = $data
  features = $features
  ours     = $ours
  listing  = $listing
  graphics = $graphics
  gnotes   = $gnotes
}

$json = $payload | ConvertTo-Json -Depth 14 -Compress
$js = @"
// Generated by research/aso-pipeline/build.ps1 from the Google Play scrape of $($data.meta.fetchedAt).
// Do not edit by hand: re-run the pipeline instead. Every field is described in docs/data-dictionary.md.
const PAYLOAD = $json;
"@
$path = Join-Path $REPO 'assets\data.js'
$js | Out-File $path -Encoding utf8
Write-Host ("assets/data.js written: {0:N0} KB" -f ((Get-Item $path).Length / 1KB))
